// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_TEST_LOCATION'] = 'West US';
  process.env['AZURE_SUBSCRIPTION_ID'] = '3ca49042-782a-4cc9-89b5-ee1b487fe115';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodeTestGroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158?api-version=2015-05-01-preview')
  .reply(200, "{\"id\":\"/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodetestgroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158\",\"location\":\"West US\",\"name\":\"testacc6158\",\"properties\":{\"accountType\":\"Standard_LRS\",\"creationTime\":\"2015-10-09T02:52:31.8698246Z\",\"primaryEndpoints\":{\"blob\":\"https://testacc6158.blob.core.windows.net/\",\"file\":\"https://testacc6158.file.core.windows.net/\",\"queue\":\"https://testacc6158.queue.core.windows.net/\",\"table\":\"https://testacc6158.table.core.windows.net/\"},\"primaryLocation\":\"West US\",\"provisioningState\":\"Succeeded\",\"statusOfPrimary\":\"available\"},\"tags\":{\"tag1\":\"val1\",\"tag2\":\"val2\"},\"type\":\"Microsoft.Storage/storageAccounts\"}\n", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '685',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': 'caafa2fb-028c-4bc4-aded-5bbc65fe777f',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14997',
  'x-ms-correlation-request-id': 'caafa2fb-028c-4bc4-aded-5bbc65fe777f',
  'x-ms-routing-request-id': 'WESTUS:20151009T025259Z:caafa2fb-028c-4bc4-aded-5bbc65fe777f',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:52:59 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodeTestGroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158?api-version=2015-05-01-preview')
  .reply(200, "{\"id\":\"/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodetestgroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158\",\"location\":\"West US\",\"name\":\"testacc6158\",\"properties\":{\"accountType\":\"Standard_LRS\",\"creationTime\":\"2015-10-09T02:52:31.8698246Z\",\"primaryEndpoints\":{\"blob\":\"https://testacc6158.blob.core.windows.net/\",\"file\":\"https://testacc6158.file.core.windows.net/\",\"queue\":\"https://testacc6158.queue.core.windows.net/\",\"table\":\"https://testacc6158.table.core.windows.net/\"},\"primaryLocation\":\"West US\",\"provisioningState\":\"Succeeded\",\"statusOfPrimary\":\"available\"},\"tags\":{\"tag1\":\"val1\",\"tag2\":\"val2\"},\"type\":\"Microsoft.Storage/storageAccounts\"}\n", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '685',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': 'caafa2fb-028c-4bc4-aded-5bbc65fe777f',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14997',
  'x-ms-correlation-request-id': 'caafa2fb-028c-4bc4-aded-5bbc65fe777f',
  'x-ms-routing-request-id': 'WESTUS:20151009T025259Z:caafa2fb-028c-4bc4-aded-5bbc65fe777f',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:52:59 GMT',
  connection: 'close' });
 return result; }]];