// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_TEST_LOCATION'] = 'West US';
  process.env['AZURE_SUBSCRIPTION_ID'] = '3ca49042-782a-4cc9-89b5-ee1b487fe115';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .post('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodeTestGroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158/listKeys?api-version=2015-05-01-preview')
  .reply(200, "{\"key1\":\"PPArCHzsxJAilnjdrT7Au0xXjcWaXMdI96Jbha7tip5M6FjM3Lafwm8QXJgLXWDzfuMprwKHiP2yqY6iW0SCxA==\",\"key2\":\"drBsmjCy14yPlvJRCm2oL5nIij0nwnxATZ5AwSR9hVU8sdDgoOpusgzbapbzI93y/cL8UhWyJqjdNcSxhuIaEg==\"}\n", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '198',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': '32765f14-e0a6-45a3-bbbd-89b2552c2285',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': '32765f14-e0a6-45a3-bbbd-89b2552c2285',
  'x-ms-routing-request-id': 'WESTUS:20151009T025302Z:32765f14-e0a6-45a3-bbbd-89b2552c2285',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:53:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .post('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodeTestGroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158/listKeys?api-version=2015-05-01-preview')
  .reply(200, "{\"key1\":\"PPArCHzsxJAilnjdrT7Au0xXjcWaXMdI96Jbha7tip5M6FjM3Lafwm8QXJgLXWDzfuMprwKHiP2yqY6iW0SCxA==\",\"key2\":\"drBsmjCy14yPlvJRCm2oL5nIij0nwnxATZ5AwSR9hVU8sdDgoOpusgzbapbzI93y/cL8UhWyJqjdNcSxhuIaEg==\"}\n", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '198',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': '32765f14-e0a6-45a3-bbbd-89b2552c2285',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': '32765f14-e0a6-45a3-bbbd-89b2552c2285',
  'x-ms-routing-request-id': 'WESTUS:20151009T025302Z:32765f14-e0a6-45a3-bbbd-89b2552c2285',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:53:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodeTestGroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158/regenerateKey?api-version=2015-05-01-preview', '*')
  .reply(200, "{\"key1\":\"DhVloqWP5VHsg4PDUQEEBaMnCz7XiT8qqxQvmKrCp8QJegGsgrzFZ0QInMp12Gfl3O1Vy+5w13MDFt36wWMHcQ==\",\"key2\":\"drBsmjCy14yPlvJRCm2oL5nIij0nwnxATZ5AwSR9hVU8sdDgoOpusgzbapbzI93y/cL8UhWyJqjdNcSxhuIaEg==\"}\n", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '198',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': '08acccb5-d67b-46c5-8c67-5ff917571436',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': '08acccb5-d67b-46c5-8c67-5ff917571436',
  'x-ms-routing-request-id': 'WESTUS:20151009T025304Z:08acccb5-d67b-46c5-8c67-5ff917571436',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:53:04 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodeTestGroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158/regenerateKey?api-version=2015-05-01-preview', '*')
  .reply(200, "{\"key1\":\"DhVloqWP5VHsg4PDUQEEBaMnCz7XiT8qqxQvmKrCp8QJegGsgrzFZ0QInMp12Gfl3O1Vy+5w13MDFt36wWMHcQ==\",\"key2\":\"drBsmjCy14yPlvJRCm2oL5nIij0nwnxATZ5AwSR9hVU8sdDgoOpusgzbapbzI93y/cL8UhWyJqjdNcSxhuIaEg==\"}\n", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '198',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': '08acccb5-d67b-46c5-8c67-5ff917571436',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': '08acccb5-d67b-46c5-8c67-5ff917571436',
  'x-ms-routing-request-id': 'WESTUS:20151009T025304Z:08acccb5-d67b-46c5-8c67-5ff917571436',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:53:04 GMT',
  connection: 'close' });
 return result; }]];