// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_TEST_LOCATION'] = 'West US';
  process.env['AZURE_SUBSCRIPTION_ID'] = '3ca49042-782a-4cc9-89b5-ee1b487fe115';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodeTestGroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158?api-version=2015-05-01-preview', '*')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/providers/Microsoft.Storage/operations/e4bf0edf-4e6d-4f6b-9263-ffb9d21395b6?monitor=true&api-version=2015-05-01-preview',
  'retry-after': '25',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-request-id': 'b13bbbfe-39bf-40b4-ae49-e183c82f1e62',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-correlation-request-id': 'b13bbbfe-39bf-40b4-ae49-e183c82f1e62',
  'x-ms-routing-request-id': 'WESTUS:20151009T025232Z:b13bbbfe-39bf-40b4-ae49-e183c82f1e62',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:52:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodeTestGroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158?api-version=2015-05-01-preview', '*')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/providers/Microsoft.Storage/operations/e4bf0edf-4e6d-4f6b-9263-ffb9d21395b6?monitor=true&api-version=2015-05-01-preview',
  'retry-after': '25',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-request-id': 'b13bbbfe-39bf-40b4-ae49-e183c82f1e62',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-correlation-request-id': 'b13bbbfe-39bf-40b4-ae49-e183c82f1e62',
  'x-ms-routing-request-id': 'WESTUS:20151009T025232Z:b13bbbfe-39bf-40b4-ae49-e183c82f1e62',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:52:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/providers/Microsoft.Storage/operations/e4bf0edf-4e6d-4f6b-9263-ffb9d21395b6?monitor=true&api-version=2015-05-01-preview')
  .reply(200, "{\"location\":\"West US\",\"tags\":{\"tag1\":\"val1\",\"tag2\":\"val2\"},\"properties\":{\"accountType\":\"Standard_LRS\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '103',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': 'e2593e1b-7afc-4c34-befc-563fce731c60',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': 'e2593e1b-7afc-4c34-befc-563fce731c60',
  'x-ms-routing-request-id': 'WESTUS:20151009T025258Z:e2593e1b-7afc-4c34-befc-563fce731c60',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:52:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/providers/Microsoft.Storage/operations/e4bf0edf-4e6d-4f6b-9263-ffb9d21395b6?monitor=true&api-version=2015-05-01-preview')
  .reply(200, "{\"location\":\"West US\",\"tags\":{\"tag1\":\"val1\",\"tag2\":\"val2\"},\"properties\":{\"accountType\":\"Standard_LRS\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '103',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': 'e2593e1b-7afc-4c34-befc-563fce731c60',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': 'e2593e1b-7afc-4c34-befc-563fce731c60',
  'x-ms-routing-request-id': 'WESTUS:20151009T025258Z:e2593e1b-7afc-4c34-befc-563fce731c60',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:52:57 GMT',
  connection: 'close' });
 return result; }]];