// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_TEST_LOCATION'] = 'West US';
  process.env['AZURE_SUBSCRIPTION_ID'] = '3ca49042-782a-4cc9-89b5-ee1b487fe115';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodeTestGroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158?api-version=2015-05-01-preview')
  .reply(200, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-request-id': '8af592d9-7aa0-4ded-a209-a3350e5de268',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-correlation-request-id': '8af592d9-7aa0-4ded-a209-a3350e5de268',
  'x-ms-routing-request-id': 'WESTUS:20151009T025306Z:8af592d9-7aa0-4ded-a209-a3350e5de268',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:53:06 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/3ca49042-782a-4cc9-89b5-ee1b487fe115/resourceGroups/nodeTestGroup3593/providers/Microsoft.Storage/storageAccounts/testacc6158?api-version=2015-05-01-preview')
  .reply(200, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-request-id': '8af592d9-7aa0-4ded-a209-a3350e5de268',
  server: 'Microsoft-HTTPAPI/2.0',
  'x-ms-correlation-request-id': '8af592d9-7aa0-4ded-a209-a3350e5de268',
  'x-ms-routing-request-id': 'WESTUS:20151009T025306Z:8af592d9-7aa0-4ded-a209-a3350e5de268',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Fri, 09 Oct 2015 02:53:06 GMT',
  connection: 'close' });
 return result; }]];